[db]
user = "root"
password = "ptNetFCcvTtCmefnLqzZkjXyctJWLxhi"
host = "switchyard.proxy.rlwy.net"
port = 59085
database = "edupointx"

[db1]
user = "root"
password = ""
host = "localhost"
port = 3306
database = "edupointx"
